name: Release

on:
  push:
    branches:
      - "main"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - uses: actions/setup-node@v4
        with:
          node-version: 23
          cache: "npm"
          cache-dependency-path: package-lock.json
      - uses: fregante/daily-version-action@v2
        name: Create tag if necessary
        id: daily-version
      - if: steps.daily-version.outputs.created
        name: "Update extension's meta"
        run: npx --yes dot-json@1 ./package.json version ${{ steps.daily-version.outputs.version  }}
      - name: install
        run: npm ci || npm install
      - name: Build & zip artifacts
        run: |
          npm run zip
          npm run zip:firefox
      - if: steps.daily-version.outputs.created
        name: Create Github release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create "${{ steps.daily-version.outputs.version }}" --generate-notes .output/*.zip
      - name: Submit to stores
        env:
          CHROME_EXTENSION_ID: ${{ vars.CHROME_EXTENSION_ID }}
          CHROME_CLIENT_ID: ${{ secrets.CHROME_CLIENT_ID }}
          CHROME_CLIENT_SECRET: ${{ secrets.CHROME_CLIENT_SECRET }}
          CHROME_REFRESH_TOKEN: ${{ secrets.CHROME_REFRESH_TOKEN }}

          FIREFOX_EXTENSION_ID: ${{ vars.FIREFOX_EXTENSION_ID }}
          FIREFOX_JWT_ISSUER: ${{ secrets.FIREFOX_JWT_ISSUER }}
          FIREFOX_JWT_SECRET: ${{ secrets.FIREFOX_JWT_SECRET }}
        run: |
          npm run env -- wxt submit \
           --chrome-zip .output/*-chrome.zip \
           --firefox-zip .output/*-firefox.zip --firefox-sources-zip .output/*-sources.zip
