name: Test

on:
  pull_request:
    branches:
      - main
      - release-*
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - uses: actions/setup-node@v4
        with:
          node-version: 23
          cache: "npm"
          cache-dependency-path: package-lock.json
      - run: npm install
      - run: npm test
